### ISSUE TITLE
Compile error: no method named `open_db_with_flags`

### ISSUE THREAD

**Issue by m4tsuri** [gio256/erigon-db#5]
Error when compiling

```rust
error[E0599]: no method named `open_db_with_flags` found for struct `libmdbx::Transaction<'env, M, NoWriteMap>` in the current scope
   --> /home/m4tsuri/.cargo/git/checkouts/erigon-db-118ee4f05d317cb2/f1a7261/src/kv/mod.rs:142:24
    |
142 |             self.inner.open_db_with_flags(Some(Db::NAME), flags)?,
    |                        ^^^^^^^^^^^^^^^^^^ method not found in `libmdbx::Transaction<'env, M, NoWriteMap>`
    |
    = note: the method was found for
            - `libmdbx::Transaction<'env, RW, E>`
```

- `erigon_db`: version: [f1a7261](https://github.com/gio256/erigon-db/commit/f1a7261fb56b5e67203fb572008a21ae9ab83ae8)
- rust version: rustc 1.65.0-nightly (c07a8b4e0 2022-08-26)

**Comment by gio256** [comment]
This method isn't exposed by libmdbx, so the repo currently uses a patched version of that library.
https://github.com/vorot93/libmdbx-rs/compare/master...gio256:libmdbx-rs:develop

Probably cargo is not pulling in that patch for you. If you are using erigon-db as a dependency in another crate, try adding this to your `Cargo.toml`:
https://github.com/gio256/erigon-db/blob/f1a7261fb56b5e67203fb572008a21ae9ab83ae8/Cargo.toml#L56-L57

**Comment by m4tsuri** [comment]
Thank you very much. Now it works well. Good crate.
